# Pipeline to force unlock TF state
# Required run time variables:
#
# lockId - the lock Id locking the state that is to be removed

name: terraform-force-unlock-canary

trigger: none

pool: terraform

variables:
  environment: canary
  keyvaultName: KEYVAULTNAME

stages:
- template: tempaltes/tf-force-unlock.yml
